### ISSUE TITLE
Necrobot#.exe

### ISSUE THREAD

**Issue by petpetpetvm** [msx752/MSniper#12]
Hopefully, it's not my only problem, i'm running multiple bots with Proxifier (for some reason, i love Proxifier more than bot setting, and easier to control)
is there anyway that MSniper can detect Necrobot*.exe ?
like Necrobot1 or Necrobot10 or maybe Necrobot100 (i don't think that anyone using 100 bots lol)
Thanks

**Comment by msx752** [comment]
@petpetpetvm wow 100 bots :)))
okey :+1:

**Comment by msx752** [comment]
It was developed for the next version v1.0.4  758a5a83563b26ad3df2f58294c2b35effb40767

**Comment by petpetpetvm** [comment]
Please release it asap :'( It's sound sooo cooolllll

**Comment by msx752** [comment]
i am working on special pokemon live feed for MSniper

be patient :+1:
