### ISSUE TITLE
Error: v1.0.4 is not working

### ISSUE THREAD

**Issue by TakRiuto** [msx752/MSniper#13]
It runs smoothly, but only that. It never detect the bot

**Comment by msx752** [comment]
@TakRiuto  whats your necrobot exe name ?

**Comment by TakRiuto** [comment]
@msx752 NecroBot.exe (Original name)

**Comment by msx752** [comment]
can you run msniper as administrator

**Comment by TakRiuto** [comment]
![captura de pantalla 81](https://cloud.githubusercontent.com/assets/20828447/18188789/ce0e5282-7082-11e6-967b-b7280d8eaa27.png)

Nothing remains the same. But I realized that did not generate the file Settings.json automatically. I will try to run the previous version to see if that works settings.json

**Comment by msx752** [comment]
did you download v1.0.4 automatically with v1.0.3  because v1.0.3 won't work, so you should download new version [https://github.com/msx752/MSniper/releases/download/1.0.4/MSniper.v1.0.4.zip](https://github.com/msx752/MSniper/releases/download/1.0.4/MSniper.v1.0.4.zip). and delete all old bot files

**Comment by TakRiuto** [comment]
Yes, is working now, Settings.json It is not generated automatically when you start MSniper. I as I did a clean install (not actualize, I delete and download the new version) and so my problem, if installed from scratch does not generate the file. And is working properly now :D

**Comment by TakRiuto** [comment]
Thanks for all ^^

**Comment by msx752** [comment]
**solution**  delete TEMP folder in project folder
