### ISSUE TITLE
Msniper v1.0.4 can't work with NecroBot v0.9.7

### ISSUE THREAD

**Issue by oZacDo** [msx752/MSniper#14]
Msniper v1.0.3 works normally
![image](https://cloud.githubusercontent.com/assets/21005066/18199849/c97279e4-7134-11e6-8030-e6055b172f02.png)

Then, I download Msniper v1.04 directly wtihout using autoupdate.
It can't work.
I alway get black window without message such as (sending to XXX: Pickhu Vaporeon 22.298026,114.166368) 
![image](https://cloud.githubusercontent.com/assets/21005066/18199975/45a2c49c-7135-11e6-8bac-902945dbc391.png)

**Comment by msx752** [comment]
@oZacDo  i think broken necrobot exe working background,so msniper can't access. close all bot and reopen. also you should wait for until necrobot is fully opened.

also i am interested.

**Comment by oZacDo** [comment]
I try close necrobot, and restart but it doesn't solve my problem.
I may use v1.0.3 instead of v1.0.4 first.
I think v1.0.4 connect to necrobot with some problem.
SnipeMS.json doesn't appear in necrobot folder.

**Comment by msx752** [comment]
correct now i am releasing hot fix 1.0.5
