### ISSUE TITLE
Manual Input Pokemon and Coord

### ISSUE THREAD

**Issue by TakRiuto** [msx752/MSniper#2]
This can make possible use coords for IV 100 pokemon (as PokeSniper 2) and dont depend for external websites

**Comment by msx752** [comment]
@TakRiuto you need autosnipping  but MSniper is manual snipping, 

 NecroBot already have function which useful for you. activating with **SnipeAtPokestops**.
also pokesniper 2 using self website for receiving pokemonlist, so dependent ?

look at SnipeConfig under config.json

**Comment by msx752** [comment]
@TakRiuto did you mean custom paste to console like `Dragonite 12.123,24.567`

added in next release:+1:  5700cdc4d8864412d28570c49a75d0d2cb0ed4c6
