### ISSUE TITLE
Access is denied

### ISSUE THREAD

**Issue by alvin0111** [msx752/MSniper#22]
I get this message "Access is denied", could you help me? Thanks.

**Comment by msx752** [comment]
@alvin0111 can you run as administrator

**Comment by alvin0111** [comment]
@msx752 :100:  Problem solved. Thanks!
i have one question more. How can I paste pokemon location data in console? I tried to use Ctrl+V or Right click, but it seems not right.

**Comment by msx752** [comment]
first copy location after that click right mouse in console
