### ISSUE TITLE
double space between name and coord

### ISSUE THREAD

**Issue by czerua** [msx752/MSniper#24]
able to modify so that a double space will not cause a format error??

when i copy the coord, i need to delete the double spacing in order to use the copy paste function of the msniper

**Comment by msx752** [comment]
@czerua can you give me an example text

**Comment by czerua** [comment]
Dratini 34.651330,135.508143 this was what i copied,

but msniper only accept Dratini 34.651330,135.508143

**Comment by msx752** [comment]
next release i will add mass space between name and coord
