### ISSUE TITLE
Apparently it keeps dsp when snipe, IDK what is the issue

### ISSUE THREAD

**Issue by kje999** [msx752/MSniper#25]
In using MSniper I send data to snipe through the MSnipe while using the necrbot private, then sometimes it keeps dsp even though the Pokemon is not expired yet, but when I try to test PokeSniper 2 it catches perfectly. IDK what is the issu with this MSniper. Also cannot accept the format of Lickitung and Tauros even if i have the correct format.

**Comment by msx752** [comment]
İ know its happen, i am working a new msniper service. İt has a different catchsystem and method. İntegrated with necrobot2 in The future.
