### ISSUE TITLE
Can not open Msniper

### ISSUE THREAD

**Issue by alvin0111** [msx752/MSniper#26]
I got this issue with v1.0.6.2, windows 8x64. Could you pls help me to solve this? Thanks.
![image](https://cloud.githubusercontent.com/assets/21995175/18577816/7f0bf870-7c16-11e6-90b4-293f99af7b77.png)
![image](https://cloud.githubusercontent.com/assets/21995175/18577830/8c667c02-7c16-11e6-81ca-ae794a65c3e0.png)

**Comment by msx752** [comment]
screen1: make sure that msniper.exe and resetallsnipe.bat in the same folder

screen2: paste format disabled for temporary, i didn't see wrong ? it works
