### ISSUE TITLE
[Request] Linking PogoLocationFeeder to Msniper

### ISSUE THREAD

**Issue by dlim1126** [msx752/MSniper#29]
is there any possible to link PoGoLocationFeeder to Msniper ?
i tried to change the Msniper.exe to Pokesniper2.exe , it sucess to link into Msniper (which the Pokesniper2.exe is) . but due to format issue , it became like this .

![msniper](https://cloud.githubusercontent.com/assets/22090697/18616018/d0376ffa-7de6-11e6-8651-d60cb0434732.JPG)

**Comment by msx752** [comment]
it disabled for temporary, i will activate later

**Comment by dodxdrwn** [comment]
same too with pokezz.com or pokedexs.com
i want to link the poke snipe button from this website to use it with Msniper (alter the configuration from using PokeSniper2.exe to Msniper.exe but no luck).
Any possibilities?

**Comment by msx752** [comment]
you right, i will activate in the nearest time
