### ISSUE TITLE
Can't compile last version

### ISSUE THREAD

**Issue by Yishaqel** [msx752/MSniper#3]
![](https://i.gyazo.com/ce13a59b9335df5b501f6278a0e9e807.png)

**Comment by Yishaqel** [comment]
Fixed when I copy the .dll from last version

**Comment by Yishaqel** [comment]
But giving me errors when I try to open, I'll use the other version

**Comment by msx752** [comment]
please redownload it and try

**Comment by Yishaqel** [comment]
it's working now

**Comment by Yishaqel** [comment]
i will try manual snipe, let's see if works

**Comment by msx752** [comment]
@tr1p0z  i already added in latest version :+1:  https://github.com/msx752/MSniper/releases/latest

**Comment by Yishaqel** [comment]
All fine now, thanks for your job dude =)
