### ISSUE TITLE
Msniper won't create protocol

### ISSUE THREAD

**Issue by shinichi19** [msx752/MSniper#31]
Hi, i was run registerProtocol.bat but when i open msniper.com in browser and click msniper. It won't affect.
when i run registerProtocol.bat as administrator windows cannot find Msniper.

What should i do ?

Thanks

![image](https://cloud.githubusercontent.com/assets/20888035/18746220/6965dd36-80f0-11e6-8025-7962e2ca67d9.png)

**Comment by msx752** [comment]
@shinichi19  https://github.com/Necrobot-Private/NecroBot/issues/259
