### ISSUE TITLE
auto web msniper

### ISSUE THREAD

**Issue by zsatanxz** [msx752/MSniper#32]
not work i'm set pokemon not catch

**Comment by msx752** [comment]
@zsatanxz if you activate auto msniper, it will work on new coming pokemons, so it doesn't snipe already listed pokemon when you set ON.

**Comment by zsatanxz** [comment]
Webpage show set on
Msniper can't work
I'm runing necrobot
Set config necrobot active

**Comment by msx752** [comment]
is popup enabled ?, or did you use any adblock or javascript blocker, because it works with javascript ?
also web-browser is important, you should use chrome
