### ISSUE TITLE
Wrong format error 

### ISSUE THREAD

**Issue by darkmanvale** [msx752/MSniper#4]
https://gyazo.com/56bcb3d2548ed518c530977229573098

I tried:
Jynx 22.284732, 114.189869
Jynx 22.284732,114.189869
Jynx22.284732,114.189869
'Jynx 22.284732, 114.189869'

but it´s the same error every time

even the example isnt working for me

**Comment by msx752** [comment]
@darkmanvale  remove every space **except after PokemonName**

paste `Jynx 22.284732,114.189869`

@darkmanvale  Also make sure using **NecroBot.v0.9.5 or upper** and **already running any NecroBot** at the moment

**Comment by dodxdrwn** [comment]
Would u mind give a tutorial how to manually adding location to MSniper?

**Comment by msx752** [comment]
İt's disabled For temporary. İ will activate in The future
