### ISSUE TITLE
Error: Index was outside the bounds of the array

### ISSUE THREAD

**Issue by masterpowers** [msx752/MSniper#8]
This Happens when i run my Bot in background...
When i Snipe it just throw this error

**Comment by msx752** [comment]
@masterpowers  wait for the opening NecroBot.
when you see username on necrobot console title then try. if you already see and still going, i think you should runas msniper with administrator authority.

inform me after trying

**Comment by langit7** [comment]
i can cnfirm if you run necro from cmd command not direct execute the exe sniper will not work.
